[package]
name = "test-globals"
version = "0.1.0"
authors = [""]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []

[dependencies]
holochain_wasm_utils = { path = "C:/github/holochain-rust/wasm_utils"}
hdk = { path = ".." }